2022-02-08 08:21:11,837 INFO    MainThread:634 [internal.py:wandb_internal():91] W&B internal server running at pid: 634, started at: 2022-02-08 08:21:11.837060
2022-02-08 08:21:11,838 INFO    WriterThread:634 [datastore.py:open_for_write():77] open: /workspace/graph-neural-pde/src/wandb/run-20220208_082111-test_run_1/run-test_run_1.wandb
2022-02-08 08:21:11,838 DEBUG   HandlerThread:634 [handler.py:handle_request():120] handle_request: check_version
2022-02-08 08:21:11,839 DEBUG   SenderThread:634 [sender.py:send():160] send: header
2022-02-08 08:21:11,839 DEBUG   SenderThread:634 [sender.py:send():160] send: request
2022-02-08 08:21:11,839 DEBUG   SenderThread:634 [sender.py:send_request():169] send_request: check_version
2022-02-08 08:21:12,065 DEBUG   SenderThread:634 [sender.py:send():160] send: run
2022-02-08 08:21:12,590 INFO    SenderThread:634 [sender.py:_start_run_threads():654] run started: test_run_1 with start time 1644308471
2022-02-08 08:21:12,591 DEBUG   SenderThread:634 [sender.py:send():160] send: summary
2022-02-08 08:21:12,592 INFO    SenderThread:634 [sender.py:_save_file():781] saving file wandb-summary.json with policy end
2022-02-08 08:21:12,597 DEBUG   HandlerThread:634 [handler.py:handle_request():120] handle_request: run_start
2022-02-08 08:21:13,059 WARNING MainThread:634 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-02-08 08:21:13,667 DEBUG   HandlerThread:634 [meta.py:__init__():39] meta init
2022-02-08 08:21:13,667 DEBUG   HandlerThread:634 [meta.py:__init__():53] meta init done
2022-02-08 08:21:13,667 DEBUG   HandlerThread:634 [meta.py:probe():210] probe
2022-02-08 08:21:13,667 DEBUG   HandlerThread:634 [meta.py:_setup_git():200] setup git
2022-02-08 08:21:13,678 DEBUG   HandlerThread:634 [meta.py:_setup_git():207] setup git done
2022-02-08 08:21:13,678 DEBUG   HandlerThread:634 [meta.py:_save_pip():57] save pip
2022-02-08 08:21:13,678 DEBUG   HandlerThread:634 [meta.py:_save_pip():71] save pip done
2022-02-08 08:21:13,679 DEBUG   HandlerThread:634 [meta.py:_save_conda():78] save conda
2022-02-08 08:21:14,236 WARNING MainThread:634 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-02-08 08:21:14,236 ERROR   MainThread:634 [internal.py:wandb_internal():149] Internal process interrupted.
2022-02-08 08:21:14,266 DEBUG   HandlerThread:634 [meta.py:_save_conda():86] save conda done
2022-02-08 08:21:14,266 DEBUG   HandlerThread:634 [meta.py:probe():252] probe done
2022-02-08 08:21:14,268 INFO    HandlerThread:634 [handler.py:finish():624] shutting down handler
2022-02-08 08:21:14,630 INFO    SenderThread:634 [sender.py:finish():884] shutting down sender
2022-02-08 08:21:15,073 INFO    WriterThread:634 [datastore.py:close():258] close: /workspace/graph-neural-pde/src/wandb/run-20220208_082111-test_run_1/run-test_run_1.wandb
2022-02-08 08:21:17,362 INFO    MainThread:634 [internal.py:handle_exit():78] Internal process exited
