Traceback (most recent call last):
  File "run_GNN.py", line 488, in <module>
    main(opt)
  File "run_GNN.py", line 222, in main
    opt['input_dim'] = dataset.x.shape[1]
AttributeError: 'Planetoid' object has no attribute 'x'