TypeError: 'Config' object is not callable