2022-04-08 09:29:06,603 INFO    MainThread:37352 [wandb_setup.py:_flush():75] Loading settings from /home/administrator/.config/wandb/settings
2022-04-08 09:29:06,604 INFO    MainThread:37352 [wandb_setup.py:_flush():75] Loading settings from /home/administrator/hieu/graph-neural-pde/src/wandb/settings
2022-04-08 09:29:06,604 INFO    MainThread:37352 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-08 09:29:06,604 INFO    MainThread:37352 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'src/test_multiple_planetoid_splits.py', 'program': 'test_multiple_planetoid_splits.py'}
2022-04-08 09:29:06,604 INFO    MainThread:37352 [wandb_init.py:_log_setup():438] Logging user logs to /home/administrator/hieu/graph-neural-pde/src/wandb/run-20220408_092906-5_tbl_1_nlr_grand_citeseer/logs/debug.log
2022-04-08 09:29:06,604 INFO    MainThread:37352 [wandb_init.py:_log_setup():439] Logging internal logs to /home/administrator/hieu/graph-neural-pde/src/wandb/run-20220408_092906-5_tbl_1_nlr_grand_citeseer/logs/debug-internal.log
2022-04-08 09:29:06,605 INFO    MainThread:37352 [wandb_init.py:init():472] calling init triggers
2022-04-08 09:29:06,605 INFO    MainThread:37352 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {}
2022-04-08 09:29:06,605 INFO    MainThread:37352 [wandb_init.py:init():525] starting backend
2022-04-08 09:29:06,606 INFO    MainThread:37352 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-08 09:29:06,618 INFO    MainThread:37352 [backend.py:ensure_launched():219] starting backend process...
2022-04-08 09:29:06,624 INFO    MainThread:37352 [backend.py:ensure_launched():224] started backend process with pid: 37506
2022-04-08 09:29:06,626 INFO    MainThread:37352 [wandb_init.py:init():534] backend started and connected
2022-04-08 09:29:06,633 INFO    MainThread:37352 [wandb_init.py:init():598] updated telemetry
2022-04-08 09:29:06,651 INFO    MainThread:37352 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-08 09:29:07,505 INFO    MainThread:37352 [wandb_run.py:_on_init():1922] communicating current version
2022-04-08 09:29:07,825 INFO    MainThread:37352 [wandb_run.py:_on_init():1926] got version response 
2022-04-08 09:29:07,826 INFO    MainThread:37352 [wandb_init.py:init():660] starting run threads in backend
2022-04-08 09:29:08,723 WARNING MainThread:37352 [wandb_init.py:init():1017] interrupted
Traceback (most recent call last):
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    run = wi.init()
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 671, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 221, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 439, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 225, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/administrator/anaconda3/envs/deepgrand/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
